name: Format code
description: Format code
inputs:
  github_token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
  command:
    description: 'command to format code'
    required: true
  commit_message:
    description: 'commit message'
    required: true
  working_directory:
    description: working directory
    required: false
    default: ""
runs:
  using: composite
  steps:
    - run: bash ${{ github.action_path }}/main.sh
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        ROOT_DIR: ${{ github.workspace }}
        INPUT_COMMAND: ${{ inputs.command }}
        INPUT_COMMIT_MESSAGE: ${{ inputs.commit_message }}
        EVENT_NAME: ${{ github.event_name }}
